# Generated by Django 4.2.6 on 2023-11-09 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order_number', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('postion', models.CharField(max_length=50)),
                ('hyper_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='KPI', max_length=100)),
                ('hyper_link', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hyper_link', models.CharField(max_length=300)),
                ('lesson_type', models.CharField(max_length=100)),
                ('num_lesson', models.PositiveIntegerField()),
                ('num_week', models.PositiveIntegerField()),
                ('is_session', models.BooleanField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='pages.dayofweek')),
                ('group', models.ManyToManyField(to='pages.group')),
                ('teacher', models.ManyToManyField(to='pages.teacher')),
                ('university', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.university')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.university'),
        ),
    ]
