# Generated by Django 4.2.6 on 2023-11-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
