# Generated by Django 4.2.6 on 2023-11-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.university'),
        ),
    ]
